language: node_js

stages:
  - test
  - build
  - deploy

#test:
#  stage: test
#  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"
    - npm install --loglevel http
    - npm run build

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
#  environment:
#    name: staging
#    url: https://staging.example.com
  only:
  - master
